const popularProteinSources = [
  { name: "Chicken Breast", type: "Animal-Based Protein" },
  { name: "Beef", type: "Animal-Based Protein" },
  { name: "Fish", type: "Animal-Based Protein" },
  { name: "Eggs", type: "Animal-Based Protein" },
  { name: "Dairy", type: "Animal-Based Protein" },
  { name: "Turkey", type: "Animal-Based Protein" },
  { name: "Pork", type: "Animal-Based Protein" },
  { name: "Legumes", type: "Plant-Based Protein" },
  { name: "Tofu and Tempeh", type: "Plant-Based Protein" },
  { name: "Quinoa", type: "Plant-Based Protein" },
  { name: "Nuts and Seeds", type: "Plant-Based Protein" },
  { name: "Edamame", type: "Plant-Based Protein" },
  { name: "Seitan", type: "Plant-Based Protein" },
  { name: "Whey Protein", type: "Protein Supplements" },
  { name: "Casein Protein", type: "Protein Supplements" },
  { name: "Plant-Based Protein Powders", type: "Protein Supplements" },
  { name: "Soy Protein", type: "Protein Supplements" },
];

const popularCarbSources = [
  { name: "Rice", type: "Grains and Cereals" },
  { name: "Wheat Products", type: "Grains and Cereals" },
  { name: "Oats", type: "Grains and Cereals" },
  { name: "Quinoa", type: "Grains and Cereals" },
  { name: "Barley", type: "Grains and Cereals" },
  { name: "Corn", type: "Grains and Cereals" },
  { name: "Potatoes", type: "Starchy Vegetables" },
  { name: "Sweet Potatoes", type: "Starchy Vegetables" },
  { name: "Yams", type: "Starchy Vegetables" },
  { name: "Squash", type: "Starchy Vegetables" },
  { name: "Lentils", type: "Legumes" },
  { name: "Beans", type: "Legumes" },
  { name: "Peas", type: "Legumes" },
  { name: "Bananas", type: "Fruits" },
  { name: "Apples", type: "Fruits" },
  { name: "Berries", type: "Fruits" },
  { name: "Grapes", type: "Fruits" },
  { name: "Bread", type: "Processed Foods" },
  { name: "Pasta", type: "Processed Foods" },
  { name: "Cereals", type: "Processed Foods" },
  { name: "Crackers and Snacks", type: "Processed Foods" },
  { name: "Sugar", type: "Sugary Foods" },
  { name: "Honey", type: "Sugary Foods" },
  { name: "Maple Syrup", type: "Sugary Foods" },
  { name: "Fruit Juices", type: "Sugary Foods" },
];

const popularFatSources = [
  { name: "Butter", type: "Animal-Based Fat Sources" },
  { name: "Cheese", type: "Animal-Based Fat Sources" },
  { name: "Lard", type: "Animal-Based Fat Sources" },
  { name: "Fatty Meats", type: "Animal-Based Fat Sources" },
  { name: "Cream", type: "Animal-Based Fat Sources" },
  { name: "Avocado", type: "Plant-Based Fat Sources" },
  { name: "Olive Oil", type: "Plant-Based Fat Sources" },
  { name: "Coconut Oil", type: "Plant-Based Fat Sources" },
  { name: "Nuts", type: "Plant-Based Fat Sources" },
  { name: "Seeds", type: "Plant-Based Fat Sources" },
  { name: "Whole Milk", type: "Dairy-Based Fat Sources" },
  { name: "Yogurt", type: "Dairy-Based Fat Sources" },
  { name: "Ghee", type: "Dairy-Based Fat Sources" },
  { name: "Salmon", type: "Fish and Seafood" },
  { name: "Tuna", type: "Fish and Seafood" },
  { name: "Mackerel", type: "Fish and Seafood" },
  { name: "Nut Butters", type: "Processed and Packaged Foods" },
  { name: "Dark Chocolate", type: "Processed and Packaged Foods" },
  { name: "Mayonnaise", type: "Processed and Packaged Foods" },
  { name: "Vegetable Oil", type: "Oils and Fats for Cooking" },
  { name: "Canola Oil", type: "Oils and Fats for Cooking" },
  { name: "Palm Oil", type: "Oils and Fats for Cooking" },
  { name: "Sesame Oil", type: "Oils and Fats for Cooking" },
  { name: "Egg Yolks", type: "Miscellaneous" },
  { name: "Cacao Butter", type: "Miscellaneous" },
  { name: "Tahini", type: "Miscellaneous" },
];

export { popularProteinSources, popularCarbSources, popularFatSources };
